language: node_js
node_js:
  - "14"

before_deploy:
  - yarn build

deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  files:
    - "dist/*.AppImage"
    - "dist/*.deb"
    - "dist/*.snap"
    - "dist/*.freebsd"
    - "dist/*.pacman"
    - "dist/*.rpm"
    - "dist/*.zip"
    - "dist/*.tar.gz"
  skip_cleanup: true
  on:
    tags: true
